@startuml
start

:Vecino completa formulario de postulación;
:Sistema recibe solicitud;

if (Datos válidos?) then (Sí)
  :Registrar proyecto en PostgreSQL;
  :Notificar al Administrador;
  :Administrador revisa postulación;

  if (Aprobado?) then (Sí)
    :Actualizar estado en BD = Aprobado;
    :Enviar notificación de aprobación al vecino;
  else (No)
    :Actualizar estado en BD = Rechazado;
    :Enviar notificación de rechazo al vecino;
  endif

else (No)
  :Rechazar postulación;
  :Enviar notificación de error al vecino;
endif

stop
@enduml
